[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.2"
  
[[redirects]]
  from = "https://italo-fronte.online/*"
  to = "https://meu-blog-cms.netlify.app/:splat"
  status = 301
  force = true
