backend:
  name: git-gateway
  branch: main

media_folder: "static/assets/img"
public_folder: "/assets/img"

media_library:
  name: uploadcare

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.custom_slug}}"
    preview_path: "blog/{{year}}/{{month}}/{{day}}/{{fields.custom_slug}}"
    path: "blog/{{year}}/{{month}}/{{day}}/{{fields.custom_slug}}/index"
    summary: "{{title}} — {{date}}"
    sortable_fields: ["date", "title"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Publicado?", name: "published", widget: "boolean", default: true }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug Personalizado", name: "custom_slug", widget: "string", required: true }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Autor",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
          required: false
        }
      - { label: "Categorias", name: "categories", widget: "list", allow_add: true }
      - { label: "Imagem de Capa", name: "image", widget: "image", required: false }
      - { label: "Alt da Imagem", name: "image_alt", widget: "string", required: false }
      - { label: "Descrição (SEO)", name: "description", widget: "text", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }